### ISSUE TITLE
[Question] Sparse Matrix Initialization

### ISSUE THREAD

**Issue by philbucher** [AMatrix/AMatrix#8]
Hi @pooyan-dadvand @roigcarlo ,
I know you haven't implemented this yet but maybe you know the answer already:

When I initialize a sparse matrix, will it be necessary that I know at which positions the non-zero entries are or is it enough to just specify the number of non-zero entries?

The goal is to avoid allocations while filling the matrix

I am asking this question in relation with [this function](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L949) in the BuilderAndSolver

**Comment by pooyan-dadvand** [comment]
For a CSRMatrix like we used in Kratos, it is crucial the construction phase as we are doing. Means that we should know the number of non-zeros and also we should assign i,j positions of values in starting from 0,0 in a row by row order. Actually the second restriction is the complex one and cannot be avoided for a CSRMatrix. There are other variants of sparse matrices (like CoordinateMatrix or some modified CompressedRowMatrix) which are based on a map or separate row by row allocation and don't impose such a restrictions. Unfortunately these matrices are considerably less efficient in matrix vector multiplication which make them unsuitable for our use cases.

**Comment by philbucher** [comment]
Ok thx for the detailed explanation!
